remote_theme: doctorfree/jekyll-theme-neoman
plugins:
  - jekyll-remote-theme

title: MirrorCommand
email: ronaldrecord@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  The Mirror Command Line project provides scripts to enable
  command line control of the MagicMirror system over a local network.
baseurl: ""
url: "https://mirror.neoman.dev"
twitter_username: ronrecord
github_username: doctorfree

show_downloads: false
# google_analytics: