#!/bin/bash

USER=`id -u -n`
MNT=/media/${USER}/Transcend/Pictures/MagicMirror
INS=/usr/local/MirrorCommand/pics

cd ${INS}
for subdir in *
do
    [ -d ${subdir} ] && {
        [ -L ${subdir} ] || {
            find ${subdir} -type f | while read i
            do
                [ -f ${MNT}/$i ] && {
                    cmp $i ${MNT}/$i > /dev/null && {
                        rm -f $i
                        ln -s ${MNT}/$i $i
                    }
                }
            done
        }
    }
done
