#!/bin/bash
#
# Usage: ./Install [package names]
#   If no package names are specified then all currently
#   supported packages will be installed
#
# Versions of apt prior to 1.1 do not support install by Debian filename
# You should probably be running a more recent version of apt
# On these early versions, install with the following:
#
# sudo dpkg -i "${DEB}"
# sudo apt-get install -f


SRC_NAME="MirrorCommandLine"
PKG_NAMES="MirrorCommandLine MirrorImagesPortrait ArtistsPortrait PhotographersPortrait"
PKG_VER="2.2"
SRC="${HOME}/src"

[ "$1" ] && PKG_NAMES="$*"

for PKG_NAME in ${PKG_NAMES}
do
  DEB="${SRC}/${SRC_NAME}/releases/${PKG_VER}/${PKG_NAME}_${PKG_VER}.deb"
  [ -f "${DEB}" ] || {
    echo "$DEB not found."
    for debs in ${SRC}/${SRC_NAME}/releases/*/${PKG_NAME}_*.deb
    do
      [ "${debs}" == "${SRC}/${SRC_NAME}/releases/*/${PKG_NAME}_*.deb" ] || {
        echo "Found existing packages:"
        echo "${debs}"
      }
    done
    continue
  }

  echo "Installing ${DEB}"
  sudo apt install "${DEB}"
done
