#!/bin/bash

MCL=$HOME/src/MirrorCommandLine
PICDIR="/mnt/transcend/Pictures/MagicMirror"
MAGDIR="/usr/local/MirrorCommandLine"

cp ${MCL}/etc/my_mirrorkeys ${MAGDIR}/etc/mirrorkeys
showkeys

cd ${MAGDIR}/pics

for pdir in Art Artists Fractals Gif JAV Models Moon_Maison Owls \
            Nuts_Magazine Photographers Tuigirl Water Waterfalls
do
    [ -d ${pdir} ] || {
        ln -s ${PICDIR}/${pdir} ${pdir}
    }
done
