#!/bin/bash

MCL=$HOME/src/MirrorCommandLine
PICDIR="/mnt/transcend/Pictures/MagicMirror"
MAGDIR="/usr/local/MirrorCommandLine"

[ -f ${MAGDIR}/etc/arp-devices.js ] && {
  cp ${MAGDIR}/etc/arp-devices.js ${MAGDIR}/etc/arp-devices-inst.js
}
[ -f ${MCL}/etc/my_arp-devices.js ] && {
  cp ${MCL}/etc/my_arp-devices.js ${MAGDIR}/etc/arp-devices.js
}
[ -f ${MCL}/etc/my_arp-devices-cols.js ] && {
  cp ${MCL}/etc/my_arp-devices-cols.js ${MAGDIR}/etc/arp-devices-cols.js
}
[ -f ${MCL}/etc/my_arp-devices-scenes.js ] && {
  cp ${MCL}/etc/my_arp-devices-scenes.js ${MAGDIR}/etc/arp-devices-scenes.js
}

[ -f ${MCL}/etc/my_mirrorkeys ] || {
    echo "Cannot locate ${MCL}/etc/my_mirrorkeys"
    echo "Find it and rerun this script"
    exit 1
}

cp ${MCL}/etc/my_mirrorkeys ${MAGDIR}/etc/mirrorkeys
showkeys

cd ${MAGDIR}/pics

for pdir in Art Artists Fractals Gif JAV Models Moon_Maison Owls \
            Nuts_Magazine Photographers Tuigirl Water Waterfalls
do
    [ -d ${pdir} ] || {
        ln -s ${PICDIR}/${pdir} ${pdir}
    }
done
