#!/bin/bash

for pkg in artists-portrait \
           models-portrait \
           photographers-portrait \
           mirror-images-portrait
do
    dpkg -s ${pkg} > /dev/null 2>&1
    retVal=$?
    [ ${retVal} -eq 0 ] && {
        echo "Removing ${pkg}"
        sudo apt remove ${pkg} -y
    }
done
sudo apt remove mirrorcommandline -y
