#!/bin/bash

# sudo apt remove artists-portrait -y
# sudo apt remove models-portrait -y
sudo apt remove photographers-portrait -y
sudo apt remove mirror-images-portrait -y
sudo apt remove mirrorcommandline -y
