#!/bin/bash
# preinst script for mirrorcommand
#
# see: dh_installdeb(1)

case "$1" in
    install|upgrade)
        export PATH=/usr/local/bin:$PATH
        MMHOME="/home/pi/MagicMirror"
        USER=
        GROUP=
        [ -d ${MMHOME}/config ] || {
            MMHOME=
            for homedir in /usr/local /home/*
            do
                [ "${homedir}" == "/home/*" ] && continue
                [ -d ${homedir}/MagicMirror/config ] && {
                    MMHOME="${homedir}/MagicMirror"
                    break
                }
            done
        }
        if [ "${MMHOME}" ]; then
            echo ""
            echo "Located a MagicMirror installation on this system."
            echo ""
        else
            echo ""
            echo "Unable to locate a MagicMirror installation on this system."
            echo "MagicMirror is required in order to install MirrorCommand."
            echo ""
            while true
            do
              read -p "Install MagicMirror ? ('Y'/'N'): " yn
              case $yn in
                  [Yy]*)
                      numusers=0
                      users=
                      for user in /home/*
                      do
                          [ "${user}" == "/home/*" ] && continue
                          [ -d ${user} ] && {
                              USER=`basename ${user}`
                              users="${users} ${USER}"
                              numusers=`expr ${numusers} + 1`
                          }
                      done
                      [ $numusers -gt 1 ] && {
                          echo ""
                          # Create a selection dialog to allow user to select USER
                          PS3="${BOLD}Please enter MagicMirror user (numeric or text): ${NORMAL}"
                          options=(${users})
                          select opt in "${options[@]}"
                          do
                            case "$opt,$REPLY" in
                              *)
                                  [ -d /home/${opt} ] && {
                                      USER="${opt}"
                                      break
                                  }
                                  printf "\nInvalid entry. Please try again"
                                  printf "\nEnter either a number or text of one of the menu entries\n"
                                  ;;
                            esac
                          done
                      }
                      [ "${USER}" ] || {
                          echo "No MagicMirror user found or selected. Using root."
                          USER="root"
                      }
                      [ -d /usr/local ] || mkdir /usr/local
                      cd /usr/local
                      if type -p npm > /dev/null
                      then
                        inst_npm=1
                      else
                        inst_npm=
                      fi
                      [ "${inst_npm}" ] || {
                          echo "Installing npm in /usr/local/..."
                          curl -L https://raw.githubusercontent.com/tj/n/master/bin/n -o /tmp/n
                          bash /tmp/n lts
                          npm install -g n
                      }
                      git clone https://github.com/MagicMirrorOrg/MagicMirror > /dev/null
                      GROUP=`id -g -n ${USER}`
                      chown -R ${USER}:${GROUP} MagicMirror
                      cd MagicMirror
                      MMHOME="/usr/local/MagicMirror"
                      if type -p npm > /dev/null
                      then
                        inst_npm=1
                      else
                        inst_npm=
                      fi
                      if [ "${inst_npm}" ]
                      then
                          echo "Installing MagicMirror in /usr/local/MagicMirror"
                          sudo -u ${USER} npm run install-mm > /dev/null 2>&1
                      else
                          echo "Unable to locate npm in the execution path."
                          echo "Install npm and run the MagicMirror installation"
                          echo "by executing the commands:"
                          echo ""
                          echo "cd /usr/local/MagicMirror"
                          echo "sudo -u ${USER} npm run install-mm"
                          echo ""
                      fi
                      break
                      ;;
                  [Nn]*)
                      exit 0
                      ;;
                  * )
                      echo "Please answer yes or no."
                      ;;
              esac
            done
        fi
        echo "MirrorCommand pre-installation configuration complete"
    ;;

    *)
    ;;
esac

exit 0
