#!/bin/bash
# postinst script for mirrorcommandline
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    configure)
        export PATH=/usr/local/bin:$PATH
        # Scripts for which links will be made in /usr/local/bin
        EXPORTS="camsnap chkconfig chktemp gethue getquote \
            get_temps mirror mknewartist mknewmodel mknewphotographer \
            mknewplayboy mknewtop mm mmapiactions mmgetb mmscene mmsetb mmupdall \
            module_update module_update_all play rand_back send_sms showkeys \
            updallartists updallmodels updallphotographers updalltop updarpscan \
            updartist updlinks updmodel updphotographer updtop vncview vol \
            websnap wireless_conf zerologs"
        LOCAL="myreboot myshutdown remountusb mirror_start"

        [ -d /usr/local ] || mkdir /usr/local
        [ -d /usr/local/bin ] || mkdir /usr/local/bin
        cd /usr/local/bin
        MM="/usr/local/MirrorCommandLine"
        for command in ${EXPORTS}
        do
          [ -f ${MM}/bin/${command} ] && {
            [ -f ${command} ] || ln -s ${MM}/bin/${command} .
          }
        done
        for command in ${LOCAL}
        do
          [ -f ${MM}/bin/${command} ] && {
            [ -f /usr/bin/${command} ] || {
              cp ${MM}/bin/${command} /usr/bin/${command}
              chmod 755 /usr/bin/${command}
            }
            if [ "${command}" == "remountusb" ] || [ "${command}" == "mirror_start" ]
            then
              [ -f ${command} ] || ln -s /usr/bin/${command} .
            else
              localcomm=`echo ${command} | sed -e "s/my//"`
              [ -f ${localcomm} ] || ln -s /usr/bin/${command} ${localcomm}
            fi
          }
        done
        MMHOME=/home/pi/MagicMirror
        [ -d ${MMHOME}/config ] || {
            MMHOME=
            for homedir in /usr/local /home/*
            do
                [ "${homedir}" == "/home/*" ] && continue
                [ -d ${homedir}/MagicMirror/config ] && {
                    MMHOME="${homedir}/MagicMirror"
                    break
                }
            done
        }
        if [ "${MMHOME}" ]
        then
            USER=$(stat -c '%U' ${MMHOME}/config)
            GROUP=$(stat -c '%G' ${MMHOME}/config)
            chown -R ${USER}:${GROUP} ${MM}
            for cfg in config config-notelegram
            do
              [ -d "${MMHOME}/${cfg}" ] || {
                sudo -u ${USER} mkdir "${MMHOME}/${cfg}"
              }
              cd "${MMHOME}/${cfg}"
              for config in ${MM}/${cfg}/*
              do
                [ "${config}" == "${MM}/${cfg}/*" ] && continue
                b=`basename ${config}`
                [ -d ${config} ] && {
                  [ -d $b ] || sudo -u ${USER} mkdir $b
                  cd $b
                  for subconf in ${config}/*
                  do
                    [ "${subconf}" == "${config}/*" ] && continue
                    c=`basename ${subconf}`
                    [ -f $c ] || sudo -u ${USER} cp ${subconf} .
                  done
                  cd ..
                  continue
                }
                [ -f $b ] || sudo -u ${USER} cp ${config} .
              done
            done
            [ -d "${MMHOME}/css" ] && {
              cd "${MMHOME}/css"
              for css in ${MM}/css/*
              do
                [ "${css}" == "${MM}/css/*" ] && continue
                b=`basename ${css}`
                if [ "$b" == "custom.css" ]
                then
                    if [ -f $b ]
                    then
                        [ -f custom-mirrorcommandline.css ] || {
                            sudo -u ${USER} cp ${css} custom-mirrorcommandline.css
                        }
                    else
                        sudo -u ${USER} cp ${css} .
                    fi
                else
                    [ -f $b ] || [ -d $b ] || sudo -u ${USER} cp ${css} .
                fi
              done
            }
            # Verify git is installed
            inst_git=`type -p git`
            inst_apt=`type -p apt`
            [ "${inst_git}" ] || {
                [ "${inst_apt}" ] && apt install git
            }
            # Install MagicMirror 3rd Party modules used by MirrorCommandLine
            MODULES="internet-monitor MMM-BackgroundSlideshow MMM-CoinMarketCap \
                     MMM-COVID19-SPARKLINE MMM-DarkSkyForecast MMM-DateOnly \
                     MMM-Detector MMM-GoogleAssistant MMM-GoogleMapsTraffic \
                     mmm-hue-lights MMM-iFrame MMM-InstagramView \
                     MMM-IronManGIF MMM-MacAddressScan MMM-MyScoreboard \
                     MMM-pages MMM-RAIN-RADAR MMM-Remote-Control \
                     MMM-Scenes MMM-Selfieshot MMM-Solar \
                     MMM-stocks MMM-TelegramBot MMM-TelegramCommands \
                     MMM-Tools MMM-Videoplayer MMM-YouTubeWebView"
            for module in ${MODULES}
            do
              [ -d "${MMHOME}/modules/${module}" ] || {
                [ -x "${MM}/bin/module_update" ] && {
                  sudo -u ${USER} ${MM}/bin/module_update -i ${module}
                }
              }
            done
            # Copy any installed MirrorCommandLine Google Assistant recipes
            # If any recipe of the same name already exists, do not overwrite
            RECIPE_DIR="modules/MMM-GoogleAssistant/recipes"
            [ -d "${MMHOME}/${RECIPE_DIR}" ] && {
              cd "${MMHOME}/${RECIPE_DIR}"
              for recipe in ${MM}/${RECIPE_DIR}/*
              do
                [ "${recipe}" == "${MM}/${RECIPE_DIR}/*" ] && continue
                b=`basename ${recipe}`
                if [ -f $b ]
                then
                  mcl=`echo $b | sed -e "s/\.js//"`
                  [ -f ${mcl}-mcl.js ] || {
                    sudo -u ${USER} cp ${recipe} ${mcl}-mcl.js
                  }
                else
                  sudo -u ${USER} cp ${recipe} .
                fi
              done
            }
        else
            echo "Unable to locate MagicMirror installation folder."
            echo "MirrorCommandLine config and css files in ${MM}"
            echo "have not been linked into the MagicMirror installation folder."
            echo "This must be accomplished manually."
        fi
        KEYS="/usr/local/MirrorCommandLine/etc/mirrorkeys"
        MMIP=`hostname -I | awk ' { print $1 } '`
        [ "${MMIP}" ] && {
            cat ${KEYS} | sed -e "s/keys\[MMIP\]=/keys\[MMIP\]=\'${MMIP}\'/" > /tmp/keys$$
            cp /tmp/keys$$ ${KEYS}
            rm -f /tmp/keys$$
            /usr/local/MirrorCommandLine/bin/showkeys -q
        }
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
