#!/bin/bash
# preinst script for mirrorcommandline
#
# see: dh_installdeb(1)

set -e

case "$1" in
    install|upgrade)
        MMHOME="/home/pi/MagicMirror"
        [ -d ${MMHOME}/config ] || {
            MMHOME=
            for homedir in /usr/local /home/*
            do
                [ "${homedir}" == "/home/*" ] && continue
                [ -d ${homedir}/MagicMirror/config ] && {
                    MMHOME="${homedir}/MagicMirror"
                    break
                }
            done
        }
        [ "${MMHOME}" ] || {
            echo ""
            echo "Unable to locate a MagicMirror installation on this system."
            echo "MagicMirror is required in order to install MirrorCommandLine."
            echo ""
            while true
            do
              read -p "Install MagicMirror ? ('Y'/'N'): " yn
              case $yn in
                  [Yy]*)
                      USER=
                      numusers=0
                      users=
                      for user in /home/*
                      do
                          [ "${user}" == "/home/*" ] && continue
                          [ -d ${user} ] && {
                              USER=`basename ${user}`
                              users="${users} ${USER}"
                              numusers=`expr ${numusers} + 1`
                          }
                      done
                      [ $numusers -gt 1 ] && {
                          echo ""
                          # Create a selection dialog to allow user to select USER
                          PS3="${BOLD}Please enter MagicMirror user (numeric or text): ${NORMAL}"
                          options=(${users})
                          select opt in "${options[@]}"
                          do
                            case "$opt,$REPLY" in
                              *)
                                  [ -d /home/${opt} ] && {
                                      USER="${opt}"
                                      break
                                  }
                                  printf "\nInvalid entry. Please try again"
                                  printf "\nEnter either a number or text of one of the menu entries\n"
                                  ;;
                            esac
                          done
                      }
                      [ "${USER}" ] || {
                          echo "No MagicMirror user found or selected. Exiting."
                          exit 1
                      }
                      [ -d /usr/local ] || mkdir /usr/local
                      cd /usr/local
                      git clone https://github.com/MichMich/MagicMirror > /dev/null
                      GROUP=`id -g -n ${USER}`
                      chown -R ${USER}:${GROUP} MagicMirror
                      cd MagicMirror
                      MMHOME="/usr/local/MagicMirror"
                      echo "Installing MagicMirror in /usr/local/MagicMirror"
                      sudo -u ${USER} npm install > /dev/null 2>&1
                      # sudo -u ${USER} cp config/config.js.sample config/config.js
                      break
                      ;;
                  [Nn]*)
                      exit 1
                      ;;
                  * )
                      echo "Please answer yes or no."
                      ;;
              esac
            done
        }
        MSO="${MMHOME}/.mirrorscreen"
        echo ""
        echo "Portrait mode display screens are taller than wide."
        echo "Landscape mode display screens are wider than tall."
        # Create a selection dialog to allow user to select screen orientation
        PS3="${BOLD}Please enter your display screen's orientation (numeric or text): ${NORMAL}"
        options=(Portrait Landscape Unknown)
        select opt in "${options[@]}"
        do
          case "$opt,$REPLY" in
            "Portrait",*|*,"Portrait"|"portrait",*|*,"portrait")
                if [ -f ${MSO} ]
                then
                    grep "PORTRAIT=" ${MSO} > /dev/null && {
                        grep -v "PORTRAIT=" ${MSO} > /tmp/mso$$
                        cp /tmp/mso$$ ${MSO}
                        rm -f /tmp/mso$$
                    }
                    echo "PORTRAIT=1" >> ${MSO}
                else
                    echo "PORTRAIT=1" > ${MSO}
                fi
                break
                ;;
            "Landscape",*|*,"Landscape"|"landscape",*|*,"landscape")
                if [ -f ${MSO} ]
                then
                    grep "PORTRAIT=" ${MSO} > /dev/null && {
                        grep -v "PORTRAIT=" ${MSO} > /tmp/mso$$
                        cp /tmp/mso$$ ${MSO}
                        rm -f /tmp/mso$$
                    }
                    echo "PORTRAIT=" >> ${MSO}
                else
                    echo "PORTRAIT=" > ${MSO}
                fi
                break
                ;;
            "Unknown",*|*,"Unknown"|"unknown",*|*,"unknown")
                echo "Using landscape display mode"
                if [ -f ${MSO} ]
                then
                    grep "PORTRAIT=" ${MSO} > /dev/null && {
                        grep -v "PORTRAIT=" ${MSO} > /tmp/mso$$
                        cp /tmp/mso$$ ${MSO}
                        rm -f /tmp/mso$$
                    }
                    echo "PORTRAIT=" >> ${MSO}
                else
                    echo "PORTRAIT=" > ${MSO}
                fi
                break
                ;;
            *)
                printf "\nInvalid entry. Please try again"
                printf "\nEnter either a number or text of one of the menu entries\n"
                ;;
          esac
        done
        [ -f ${MSO} ] && {
          [ "${USER}" ] || {
            USER=$(stat -c '%U' ${MMHOME}/config)
          }
          [ "${GROUP}" ] || {
            GROUP=$(stat -c '%G' ${MMHOME}/config)
          }
          [ "${USER}" ] && [ "${GROUP}" ] && chown ${USER}:${GROUP} ${MSO}
        }
    ;;

    *)
    ;;
esac

exit 0
