#!/bin/bash
# postinst script for mirrorcommandline
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    configure)
        [ -d /usr/local ] || mkdir /usr/local
        [ -d /usr/local/bin ] || mkdir /usr/local/bin
        cd /usr/local/bin
        for command in /usr/local/MagicMirror/bin/*
        do
            b=`basename ${command}`
            [ -f $b ] || ln -s ${command} .
        done
        MMHOME=/home/pi/MagicMirror
        [ -d ${MMHOME}/config ] || {
            MMHOME=
            for homedir in /home/*
            do
                [ "${homedir}" == "/home/*" ] && continue
                [ -d ${homedir}/MagicMirror/config ] && {
                    MMHOME="${homedir}/MagicMirror"
                    break
                }
            done
        }
        if [ "${MMHOME}" ]
        then
            cd "${MMHOME}/config"
            for config in /usr/local/MagicMirror/config/*
            do
                b=`basename ${config}`
                [ -f $b ] || [ -d $b ] || ln -s ${config} .
            done
            cd "${MMHOME}/css"
            for css in /usr/local/MagicMirror/css/*
            do
                b=`basename ${css}`
                if [ "$b" == "custom.css" ]
                then
                    if [ -f $b ]
                    then
                        [ -f custom-mirrorcommandline.css ] || {
                            ln -s ${css} custom-mirrorcommandline.css
                        }
                    else
                        ln -s ${css} .
                    fi
                else
                    [ -f $b ] || [ -d $b ] || ln -s ${css} .
                fi
            done
        else
            echo "Unable to locate MagicMirror installation folder."
            echo "MirrorCommandLine config and css files in /usr/local/MagicMirror"
            echo "have not been linked into the MagicMirror installation folder."
            echo "This must be accomplished manually."
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
